---
apiVersion: v1
kind: Service
metadata:
 name: snap-report-backend-service
spec:
 selector:
   # Selector for Pods
   app: snap-report-backend-app
 ports:
   # Port Map
 - port: 80
   targetPort: 8080
   protocol: TCP
 type: LoadBalancer